-- what is the total revenue generated by male vs female
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

-- which customer used a discount but still spend more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);
use customer;

-- which are the top 5 products with the highest average review rating?
select item_purchased,
round(avg(review_rating),2) as 'Average Product Rating'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
-- compare the average purchase amount between standard and express shipping?
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Do subscribed customers spend more? compare average spend and total revenue between
-- subscribed and non-subscribed
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_spend
from customer
group by subscription_status
order by total_spend,avg_spend desc;

-- which product have the highest percentage of purchases with discount applied?
select item_purchased,
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
use customer;

-- segment customer into new,returning and loyal based on their total number
-- of previous purchased, and show the count of each segment
with customer_type as(
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'loyal'
end as customer_segment
from customer
)
select customer_segment,count(*) as Number_of_customers
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products within each category?
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_order,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category, item_purchased
)
select item_rank,category, item_purchased,total_order
from item_counts
where item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age groups?
select
sum(purchase_amount) as total_revenue,
age-group
from customer
group by age-group
order by total_revenue desc;
select * from customer;